FROM ubuntu:14.04
MAINTAINER rob

## php7.1 nginx container




RUN sudo sed -i 's/archive/cn.archive/g' /etc/apt/sources.list && \
    sudo apt-get clean && \
    sudo apt-get update

RUN sudo apt-get -y install software-properties-common python-software-properties  
RUN sudo LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php


RUN sudo apt-get clean && \
    sudo apt-get update


RUN    sudo apt-get -y install vim php7.1 nginx  php7.1-dev php7.1-fpm libpcre3-dev php7.1-mysql php7.1-gd php7.1-pdo php7.1-mbstring mysql-client gcc make re2c git

RUN sudo apt-get clean

ADD ngx-site.conf /etc/nginx/sites-enabled/


WORKDIR /tmp
RUN  /usr/bin/apt-get update && \
    /usr/bin/git clone git://github.com/phalcon/cphalcon.git 

RUN cd cphalcon/build && \
    ./install --phpize /usr/bin/phpize7.1 --php-config /usr/bin/php-config7.1 && \
    cd /tmp

RUN rm -rf /tmp/cphalcon/ 

RUN /bin/echo 'extension=phalcon.so' > /etc/php/7.1/mods-available/phalcon.ini

RUN /usr/sbin/phpenmod phalcon
RUN /usr/sbin/phpdismod opcache

EXPOSE 80

RUN mkdir -p /sites/m.chinapex.com.cn/
ADD . /sites/www


CMD /sites/www/run.sh

